# Use the official Python image as a base image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the necessary files into the container
COPY requirements.txt requirements.txt
COPY pipeline/training_pipeline.py pipeline/training_pipeline.py
COPY run_pipeline.py run_pipeline.py

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the training pipeline
CMD ["python", "run_pipeline.py", "--pipeline", "training"]
